export const QUOTES = [
"Be patient toward all that is unsolved in your heart.",
"We are shaped by our thoughts; we become what we think.",
"Knowing yourself is the beginning of all wisdom.",
"What you seek is seeking you.",
"It is not length of life, but depth of life.",
"The quieter you become, the more you can hear.",
"Live as if you were to die tomorrow, learn as if you were to live forever.",
"Turn your wounds into wisdom.",
"To be yourself in a world that tries to change you is a great victory.",
"Happiness comes from your own actions.",
"You write your life with actions, not words.",
"The only way out is through.",
"Small things done with care can change everything.",
"He who has a why can endure almost any how.",
"Be soft without being weak.",
"We see the world not as it is, but as we are.",
"Freedom is what you do with what happened to you.",
"Courage begins with thinking for yourself.",
"Do not be afraid of being afraid.",
"Life expands or shrinks according to courage.",
"The meaning of life is to give life meaning.",
"Nothing leaves until it teaches what it must.",
"The privilege of life is becoming yourself.",
"Rest is not a waste of time.",
"Do not dilute what is true to you.",
"Where there is ruin, there is hope.",
"What you do matters more than you think.",
"Let go of the life you planned.",
"Sometimes you win, sometimes you learn.",
"Become someone your future self respects.",
"Silence is sometimes the best answer.",
"Growth often feels like discomfort.",
"You are allowed to change your mind.",
"Listen more than you speak.",
"Time reveals what effort conceals.",
"Consistency builds what motivation cannot.",
"Not everything requires a reaction.",
"Calm is a form of strength.",
"Healing is not linear.",
"Choose depth over distraction.",
"You can be gentle and still be powerful.",
"Comparison steals clarity.",
"Discipline creates freedom.",
"Most things are simpler than fear suggests.",
"Your habits shape your future.",
"Stillness clarifies direction.",
"Progress is often quiet.",
"Self-respect changes everything.",
"Pay attention to what drains you.",
"Peace begins with honesty.",
"You grow when you take responsibility.",
"Comfort rarely leads to growth.",
"Learn to pause before reacting.",
"Your attention is valuable.",
"What you tolerate teaches others how to treat you.",
"Slow progress is still progress.",
"Confidence is built through action.",
"You don’t need permission to evolve.",
"Simplicity reveals truth.",
"Let actions speak where words fail.",
"Awareness is the first step to change.",
"Protect your energy intentionally.",
"Choose effort over excuses.",
"Your future depends on today’s choices.",
"Clarity comes from engagement, not avoidance.",
"Learn to sit with uncertainty.",
"Focus is a competitive advantage.",
"Inner peace requires boundaries.",
"Growth demands patience.",
"What you practice becomes permanent.",
"Be curious, not judgmental.",
"Responsibility brings control.",
"Trust is built slowly and lost quickly.",
"Discipline is self-care in action.",
"Mastery requires boredom tolerance.",
"Reflection turns experience into insight.",
"Direction matters more than speed.",
"Emotional regulation is a skill.",
"Truth often feels uncomfortable first.",
"Learn to finish what you start.",
"Presence improves everything.",
"Resilience is learned through adversity.",
"Meaning comes from contribution.",
"Progress requires discomfort.",
"Choose substance over approval.",
"Self-awareness is quiet power.",
"You cannot grow what you do not measure.",
"Respect your own time.",
"Courage often feels like doubt.",
"Intentional living reduces regret.",
"Energy follows attention.",
"Small habits compound quietly.",
"Focus on what you can control.",
"Learning never ends.",
"Values guide better than rules.",
"Patience is strength under control.",
"Action clarifies intention.",
"Learn to wait without quitting.",
"You become what you repeatedly do.",
"Thoughtful effort beats talent alone.",
"Silence reveals priorities.",
"Growth requires honest feedback.",
"Choose clarity over comfort.",
"Rest supports consistency.",
"Emotional maturity is self-honesty.",
"Avoidance compounds problems.",
"Excellence is practiced daily.",
"Meaningful work requires focus.",
"Learn when to let go.",
"You teach people how to treat you.",
"Discipline outlasts motivation.",
"Curiosity expands perspective.",
"Stability comes from structure.",
"Awareness precedes improvement.",
"Consistency creates trust.",
"Direction gives effort value.",
"Self-control is quiet confidence.",
"Hard things build resilience.",
"Time rewards patience.",
"Learn to say no calmly.",
"Focus reveals priorities.",
"Growth often feels lonely.",
"Simplicity reduces noise.",
"Integrity is consistency of action.",
"Change begins with ownership.",
"Calm decisions outperform rushed ones.",
"Self-respect simplifies choices.",
"Improvement is intentional.",
"Discomfort signals growth.",
"Discipline is choosing long-term over short-term.",
"Attention determines experience.",
"Slow down to move forward.",
"Boundaries protect clarity.",
"Insight follows reflection.",
"Consistency beats intensity.",
"Emotional control strengthens leadership.",
"Learn to rest without guilt.",
"Progress hides in repetition.",
"Purpose guides endurance.",
"You don’t need to rush clarity.",
"Focus creates momentum.",
"Learn from outcomes, not intentions.",
"Self-discipline is self-trust.",
"Direction reduces anxiety.",
"Intentional living requires awareness.",
"Clarity grows from action.",
"You grow into what you nurture.",
"Effort reveals character.",
"Learn to pause before deciding.",
"Mastery is built slowly.",
"Thoughtful limits create freedom.",
"Practice shapes identity.",
"Learn to be alone comfortably.",
"Patience compounds results.",
"Focus is a daily choice.",
"Structure supports creativity.",
"Energy responds to purpose.",
"Awareness reduces reactivity.",
"Commitment clarifies priorities.",
"Meaning comes from responsibility.",
"Calm presence influences outcomes.",
"Direction creates confidence.",
"Growth demands consistency.",
"Self-control multiplies ability.",
"Learn to endure boredom.",
"Clarity simplifies effort.",
"Discipline creates reliability.",
"Purpose fuels resilience.",
"Thoughtfulness improves decisions.",
"Intentional habits shape identity.",
"Learn to wait productively.",
"Focus amplifies effort.",
"Stillness reveals direction.",
"Practice builds confidence.",
"Consistency earns trust.",
"Awareness deepens understanding.",
"Discipline reduces chaos.",
"Direction sustains motivation.",
"Growth requires patience with yourself.",
"Simplicity strengthens focus.",
"Self-honesty enables growth.",
"Control attention to control outcomes.",
"Repetition builds mastery.",
"Calm thinking outperforms panic.",
"Boundaries clarify priorities.",
"Intentional action creates meaning.",
"Focus turns effort into progress.",
"Learn to finish well.",
"Direction outweighs speed.",
"Awareness sharpens choices.",
"Consistency builds momentum.",
"Discipline preserves energy.",
"Growth is earned daily.",
"Stillness improves judgment.",
"Purpose organizes effort.",
"Self-control creates options.",
"Learning never stops.",
"Intentional focus reduces regret.",
"Practice strengthens clarity.",
"Calm confidence is built quietly.",
"Discipline is freedom in disguise.",
"Awareness changes behavior.",
"Growth requires repetition.",
"Focus reveals value.",
"Boundaries protect energy.",
"Purpose fuels persistence.",
"Direction shapes outcomes.",
"Self-discipline builds respect.",
"Clarity reduces stress.",
"Learning sharpens perspective.",
"Consistency compounds results.",
"Calm effort beats frantic action.",
"Intentional choices build identity.",
"Awareness prevents reaction.",
"Focus improves quality.",
"Growth follows patience.",
"Discipline creates stability.",
"Purpose gives effort meaning.",
"Stillness supports insight.",
"Learning strengthens adaptability.",
"Direction sustains progress.",
"Self-control improves outcomes.",
"Focus is practiced daily.",
"Growth demands accountability.",
"Calm presence inspires trust.",
"Intentional living requires effort.",
"Discipline sharpens priorities.",
"Awareness clarifies motives.",
"Purpose directs energy.",
"Consistency builds confidence.",
"Focus creates depth.",
"Learning encourages humility.",
"Direction reduces distraction.",
"Self-discipline builds freedom.",
"Growth rewards persistence.",
"Calm thinking supports clarity.",
"Intentional habits shape results.",
"Awareness strengthens control.",
"Focus multiplies impact.",
"Discipline builds resilience.",
"Purpose sustains effort.",
"Learning improves judgment.",
"Direction guides consistency.",
"Self-control enables patience.",
"Growth follows commitment.",
"Calm effort lasts longer.",
"Intentional action creates progress.",
"Awareness supports balance.",
"Focus enhances meaning.",
"Discipline simplifies decisions.",
"Purpose fuels growth.",
"Learning expands capacity.",
"Direction defines success.",
"Self-discipline earns trust.",
"Growth is cumulative.",
"Calm presence improves outcomes.",
"Intentional focus strengthens resolve.",
"Awareness refines behavior.",
"Discipline builds reliability.",
"Purpose aligns effort.",
"Learning sustains growth.",
"Direction keeps momentum.",
"Self-control preserves energy.",
"Growth demands patience.",
"Calm focus improves quality.",
"Intentional habits build strength.",
"Awareness deepens insight.",
"Discipline creates order.",
"Purpose organizes priorities.",
"Learning supports resilience.",
"Direction anchors effort.",
"Self-discipline builds consistency.",
"Growth follows intention.",
"Calm thinking supports endurance.",
"Intentional living reduces noise.",
"Awareness enhances clarity.",
"Focus strengthens execution.",
"Discipline builds momentum.",
"Purpose sustains motivation.",
"Learning sharpens skill.",
"Direction channels effort.",
"Self-control builds confidence.",
"Growth rewards consistency.",
"Calm presence strengthens leadership.",
"Intentional focus builds progress.",
"Awareness improves decisions.",
"Discipline refines habits.",
"Purpose fuels action.",
"Learning broadens understanding.",
"Direction sustains clarity.",
"Self-discipline strengthens resolve.",
"Growth is earned slowly.",
"Calm effort builds trust.",
"Intentional habits create stability.",
"Awareness supports growth.",
"Focus enhances effectiveness.",
"Discipline builds mastery.",
"Purpose gives direction.",
"Learning supports adaptability.",
"Direction reduces uncertainty.",
"Self-control improves patience.",
"Growth follows discipline.",
"Calm thinking improves outcomes.",
"Intentional effort compounds.",
"Awareness guides action.",
"Focus creates excellence.",
"Discipline shapes character.",
"Purpose sustains progress.",
"Learning refines judgment.",
"Direction strengthens commitment.",
"Self-discipline builds integrity.",
"Growth requires consistency.",
"Calm presence improves clarity.",
"Intentional focus builds momentum.",
"Awareness reduces mistakes.",
"Discipline creates reliability.",
"Purpose aligns action.",
"Learning sustains curiosity.",
"Direction channels growth.",
"Self-control builds endurance.",
"Growth rewards patience.",
"Calm effort lasts.",
"Intentional habits build success.",
"Awareness strengthens self-trust.",
"Focus improves depth.",
"Discipline creates freedom.",
"Purpose fuels endurance.",
"Learning improves perspective.",
"Direction anchors discipline.",
"Self-discipline builds confidence.",
"Growth follows clarity.",
"Calm presence improves focus.",
"Intentional effort builds meaning.",
"Awareness shapes behavior.",
"Discipline strengthens resilience.",
"Purpose sustains effort.",
"Learning supports progress.",
"Direction clarifies goals.",
"Self-control preserves clarity.",
"Growth is cumulative.",
"Calm thinking improves judgment.",
"Intentional focus builds strength.",
"Awareness refines action.",
"Discipline creates momentum.",
"Purpose organizes life.",
"Learning sharpens insight.",
"Direction sustains focus.",
"Self-discipline builds reliability.",
"Growth follows effort.",
"Calm presence builds trust.",
"Intentional habits shape outcomes.",
"Awareness improves consistency.",
"Focus enhances execution.",
"Discipline builds character.",
"Purpose fuels persistence.",
"Learning deepens understanding.",
"Direction reduces distraction.",
"Self-control supports patience.",
"Growth rewards intention.",
"Calm effort creates stability.",
"Intentional focus sustains progress.",
"Awareness strengthens discipline.",
"Focus reveals purpose.",
"Discipline builds freedom.",
"Growth continues as long as you do.",
]
