export const QUOTES = [
  "Intelligence begins where calculation ends.",
  "A fast answer is not always a thoughtful one.",
  "Technology amplifies intent, not wisdom.",
  "Automation reveals what we value most.",
  "Efficiency without direction is noise.",
  "A system is only as thoughtful as its goals.",
  "Knowledge scales faster than understanding.",
  "The future rewards clarity, not complexity.",
  "Thinking is choosing what to ignore.",
  "Optimization is meaningless without purpose.",
  "Machines process information; humans assign meaning.",
  "Speed is impressive, judgment is rare.",
  "The best tools disappear into intention.",
  "Progress is knowing what not to automate.",
  "Intelligence is restraint applied correctly.",
  "Capability grows faster than responsibility.",
  "A smarter system asks better questions.",
  "Data explains patterns, not priorities.",
  "Automation reveals assumptions at scale.",
  "Wisdom is context remembered.",
  "The most powerful choice is where attention goes.",
  "Prediction is easier than understanding.",
  "Technology solves problems we define.",
  "What scales fastest is rarely what matters most.",
  "A model reflects its incentives.",
  "The future belongs to deliberate thinkers.",
  "Complexity hides in unexamined goals.",
  "Intelligence is alignment over output.",
  "Tools inherit the values of their makers.",
  "Clarity outperforms cleverness.",
  "Thinking slows the right things down.",
  "Efficiency magnifies intention.",
  "Machines answer; humans decide.",
  "What we automate defines what we keep.",
  "Speed without reflection is drift.",
  "Understanding cannot be parallelized.",
  "The signal is rarely loud.",
  "Intelligence is the art of prioritization.",
  "Scale tests values mercilessly.",
  "A system reveals its purpose through use.",
  "Optimization exposes tradeoffs.",
  "Wisdom is remembering consequences.",
  "The future rewards calm thinkers.",
  "Data is silent without interpretation.",
  "The best systems respect human limits.",
  "Progress requires choosing constraints.",
  "Automation makes values visible.",
  "Clarity is a competitive advantage.",
  "The most valuable output is trust.",
  "Technology accelerates decisions already made.",
  "Understanding emerges from friction.",
  "A tool’s power lies in how it’s framed.",
  "Intelligence is knowing when to stop.",
  "Scale amplifies both good and bad.",
  "The future is shaped by defaults.",
  "Thinking requires pause.",
  "What matters rarely shouts.",
  "Automation shifts responsibility, not intent.",
  "Judgment improves with context.",
  "Complexity grows where clarity is absent.",
  "The best answers create better questions.",
  "Efficiency reveals priorities.",
  "Intelligence balances speed with care.",
  "Tools should reduce regret, not thought.",
  "Wisdom anticipates second effects.",
  "The future belongs to those who reflect.",
  "Information is abundant; meaning is scarce.",
  "Design is applied philosophy.",
  "Automation magnifies human choices.",
  "Understanding takes time.",
  "The quiet solution is often correct.",
  "Intelligence is applied patience.",
  "Scale demands humility.",
  "Technology exposes assumptions.",
  "Thinking is disciplined curiosity.",
  "The best systems earn trust slowly.",
  "Progress is intentional change.",
  "Automation tests alignment.",
  "Wisdom grows through restraint.",
  "Clarity simplifies decisions.",
  "The future favors thoughtful defaults.",
  "Knowledge accumulates; understanding compounds.",
  "A system’s edges reveal its truth.",
  "Intelligence is selective focus.",
  "Tools should support judgment, not replace it.",
  "Scale rewards foresight.",
  "The right question saves time.",
  "Technology reflects priorities.",
  "Thinking creates leverage.",
  "Automation demands accountability.",
  "Wisdom sees beyond metrics.",
  "The future belongs to deliberate builders.",
  "Understanding reduces unintended consequences.",
  "Clarity precedes speed.",
  "A model is a map, not territory.",
  "Intelligence is adaptive restraint.",
  "Progress requires reflection.",
  "Automation magnifies intent.",
  "Meaning cannot be optimized.",
  "The best tools encourage thought.",
  "Scale reveals ethics.",
  "Thinking defines direction.",
  "Wisdom integrates experience.",
  "Technology accelerates outcomes, not values.",
  "Clarity reduces friction.",
  "Intelligence is contextual awareness.",
  "Automation exposes priorities.",
  "The future rewards calm judgment.",
  "Understanding resists shortcuts.",
  "Tools shape behavior.",
  "Progress follows intention.",
  "Wisdom balances possibility with care.",
  "The signal emerges over time.",
  "Intelligence is measured by outcomes.",
  "Scale magnifies alignment.",
  "Technology amplifies decisions.",
  "Thinking is deliberate effort.",
  "Automation tests foresight.",
  "Clarity anchors complexity.",
  "The future favors thoughtful systems.",
  "Understanding grows with reflection.",
  "Tools should invite responsibility.",
  "Wisdom anticipates impact.",
  "Intelligence guides capability.",
  "Scale demands ethics.",
  "Technology reveals intent.",
  "Thinking refines purpose.",
  "Automation reshapes choices.",
  "Clarity enables trust.",
  "The future belongs to intentional thinkers.",
  "Understanding informs restraint.",
  "Tools reflect design values.",
  "Wisdom sees long horizons.",
  "Intelligence aligns means with ends.",
  "Scale amplifies consequences.",
  "Technology extends reach.",
  "Thinking sets direction.",
  "Automation requires wisdom.",
  "Clarity reduces noise.",
  "The future rewards thoughtful design.",
  "Understanding tempers speed.",
  "Tools shape outcomes.",
  "Wisdom balances progress.",
  "Intelligence is conscious choice.",
  "Scale tests systems.",
  "Technology reflects human judgment.",
  "Thinking creates meaning.",
  "Automation magnifies values.",
  "Clarity guides action.",
  "The future is built deliberately.",
  "Understanding prevents regret.",
  "Tools should serve intent.",
  "Wisdom values context.",
  "Intelligence directs power.",
  "Scale reveals structure.",
  "Technology accelerates intent.",
  "Thinking requires discipline.",
  "Automation exposes tradeoffs.",
  "Clarity strengthens decisions.",
  "The future belongs to the thoughtful.",
  "Understanding resists haste.",
  "Tools influence behavior.",
  "Wisdom prioritizes impact.",
  "Intelligence is mindful action.",
  "Scale magnifies design.",
  "Technology expresses choices.",
  "Thinking defines success.",
  "Automation reshapes responsibility.",
  "Clarity fosters alignment.",
  "The future favors intentional systems.",
  "Understanding grounds progress.",
  "Tools reflect creators.",
  "Wisdom integrates foresight.",
  "Intelligence balances ambition.",
  "Scale tests intentions.",
  "Technology expands reach.",
  "Thinking informs design.",
  "Automation magnifies outcomes.",
  "Clarity supports trust.",
  "The future belongs to conscious builders.",
  "Understanding tempers power.",
  "Tools should encourage reflection.",
  "Wisdom sees beyond output.",
  "Intelligence directs scale.",
  "Technology amplifies direction.",
  "Thinking shapes value.",
  "Automation requires judgment.",
  "Clarity enables purpose.",
  "The future rewards intentionality.",
  "Understanding prevents misuse.",
  "Tools encode values.",
  "Wisdom balances efficiency.",
  "Intelligence aligns action.",
  "Scale magnifies intent.",
  "Technology extends capability.",
  "Thinking creates coherence.",
  "Automation reveals design.",
  "Clarity defines priorities.",
  "The future belongs to careful thinkers.",
  "Understanding informs action.",
  "Tools influence outcomes.",
  "Wisdom values restraint.",
  "Intelligence is purposeful focus.",
  "Scale tests ethics.",
  "Technology mirrors intent.",
  "Thinking guides progress.",
  "Automation amplifies choice.",
  "Clarity strengthens alignment.",
  "The future is intentionally shaped."
]
